window.onload=function(){if(document.getElementById('contactformcontainer')){var emptyfield=document.getElementById('emptyfield');var filledfield=document.getElementById('filledfield');emptyfield.value='changed';filledfield.value='';}}();(function(){var menuOutside=document.getElementById('menu_outside_click');var mmenu=document.getElementById('mmenu');var page=document.getElementById('content');var ham=document.getElementById('mobile_hamburger');var footer=document.getElementById('colophon');menuOutside.onclick=function(){showmmenu(ham,this,mmenu,page);}
ham.onclick=function(){showmmenu(this,menuOutside,mmenu,page);}
function showmmenu(ham,menuOutside,mmenu,page){if(!mmenu.showing){mmenu.showing=true;menuOutside.style.display='block';ham.className+=' open_ham';page.style.transform='translateX(-32%)';mmenu.style.right='-1px';footer.style.transform='translateX(-32%)';}else{mmenu.showing=null;menuOutside.style.display='none';page.style.transform='translateX(0%)';mmenu.style.right='-250px';footer.style.transform='translateX(0%)';ham.className='';}}})();window.addEventListener('scroll',function(e){var width=document.documentElement.clientWidth;if(width<768){return;}
var headernav=document.getElementById('menu-header');var headerend=document.getElementById('main');var scrollbar=document.getElementById('scrollbar');navposition=headernav.offsetTop+124;endpostion=headerend.getBoundingClientRect().top;if(navposition>=endpostion){headernav.style.backgroundColor='rgba(0,0,0, 0.66)';headernav.style.padding='20px';}
else{headernav.style.backgroundColor='rgba(0,0,0, 0)';headernav.style.padding='60px 20px 40px 20px';}
if(document.getElementById('scrollbar')){if(document.getElementById('marketingtoday_section')){var homeheaderend=document.getElementById('marketingtoday_section')
var homeendpostition=homeheaderend.getBoundingClientRect().top;if(homeendpostition<=0){scrollbar.style.opacity=1;}
else{scrollbar.style.opacity=0;}}
else{if(endpostion<=0){scrollbar.style.opacity=1;}
else{scrollbar.style.opacity=1;}}
var numitems=scrollbar.querySelectorAll('.scrollhover');var isFocused=false;for(i=1;i<=numitems.length-1;i++){var currentitem=numitems[i]
var hoversection=numitems[i].getAttribute('data-value');var pagesection=document.getElementById(hoversection)
var sectionposition=pagesection.getBoundingClientRect().top;var sectionheight=-Math.abs(pagesection.offsetHeight);if(sectionposition<=123&&sectionposition>=sectionheight&&!currentitem.isFocused){var hasHoverClass=currentitem.className.includes('hoverstate')
if(!hasHoverClass){currentitem.className+=" hoverstate";currentitem.isFocused=true;}}
if((sectionposition>124||sectionposition<sectionheight)&&currentitem.isFocused){currentitem.className="scrollhover";currentitem.isFocused=false;}}}});if(document.getElementById('clientlogogrid')){var clientBgGrid=document.getElementById('clientbackgroundgrid');var clientlogogrid=document.getElementById('clientlogos');var clientlogos=clientlogogrid.querySelectorAll('.clientbox');var clientbgs=clientBgGrid.querySelectorAll('.clientbox');var partnerBgGrid=document.getElementById('partnerbackgroundgrid');var partnerlogogrid=document.getElementById('partnerlogos');var partnerlogos=partnerlogogrid.querySelectorAll('.clientbox');var partnerbgs=partnerBgGrid.querySelectorAll('.clientbox');for(i=0;i<partnerlogos.length;i++){if(clientlogos[i]){clientlogos[i].addEventListener("mouseenter",revealbackground)
clientlogos[i].addEventListener("mouseleave",hidebackground)
clientlogos[i].index=i;clientlogos[i].type='client';}
partnerlogos[i].addEventListener("mouseenter",revealbackground)
partnerlogos[i].addEventListener("mouseleave",hidebackground)
partnerlogos[i].index=i;partnerlogos[i].type='partner';}
function revealbackground(evt){var index=evt.target.index;var type=evt.target.type;if(type=='client'){clientbgs[index].style.opacity=1;}
else{partnerbgs[index].style.opacity=1;}}
function hidebackground(evt){var index=evt.target.index;var type=evt.target.type;if(type=='client'){clientbgs[index].style.opacity=0;}
else{partnerbgs[index].style.opacity=0;}}}
if(document.getElementById('values_section')){window.addEventListener('scroll',function(e){var width=document.documentElement.clientWidth;if(width<768){return;}
var headernav=document.getElementById('menu-header');var tableheader=document.getElementById('tableheader');var stickyheader=document.getElementById('stickyheader');var navposition=headernav.offsetTop+70;var stickyheaderposition=stickyheader.offsetTop+30;var stickystart=tableheader.getBoundingClientRect().top;var stickyend=tableheader.getBoundingClientRect().bottom+878;if(navposition>=stickystart){tableheader.style.opacity=0;stickyheader.style.opacity=1;}
if(stickyheaderposition>=stickyend||stickyheaderposition<stickystart){tableheader.style.opacity=1;stickyheader.style.opacity=0;}});}
function init(){var mapOptions={zoom:16,center:new google.maps.LatLng(43.649145,-79.394461),scrollwheel:false,navigationControl:false,mapTypeControl:false,scaleControl:false,draggable:false,styles:[{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#000000"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":21}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":16}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":19}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":17}]}]};var mapElement=document.getElementById('map');var map=new google.maps.Map(mapElement,mapOptions);var icon={url:'https://www.abacus.agency/wp-content/uploads/2017/03/mappin.png',scaledSize:new google.maps.Size(25,35),}
var marker=new google.maps.Marker({position:new google.maps.LatLng(43.649145,-79.394461),map:map,icon:icon,optimized:false});marker.setMap(map);}
function sendtodb(url,formtype){var oname=document.getElementById('name');var oemail=document.getElementById('email');var ophone=document.getElementById('phone');var orange=document.getElementById('range');var omessage=document.getElementById('message');var valid=1;var offender=null;var errormsg='';if(oemail){if(!valemail(oemail)){valid=0;offender=offender||oemail;errormsg='Invalid email'}}
if(oname){if(!valstr(oname)){valid=0;offender=offender||oname;errormsg='Required fields are empty'}}
if(orange){if(!valstr(orange)){valid=0;offender=offender||orange;errormsg='Required fields are empty'}}
if(oname){if(!valstr(omessage)){valid=0;offender=offender||oname;errormsg='Required fields are empty'}}
if(!valid){document.getElementById('errormsg').style='color:red';document.getElementById('errormsg').innerHTML=errormsg;return;}
var name=oname.value;var email=oemail.value;var phone=ophone.value;var range=orange.value;var message=omessage.value;var filledvalue=document.getElementById('emptyfield').value;var emptyvalue=document.getElementById('filledfield').value;var subject=document.getElementById('opensubject').value;var params=[];params.push('name='+name);params.push('email='+email);params.push('phone='+phone);params.push('message='+message);params.push('range='+range);params.push('subject='+subject);params.push('filledvalue='+filledvalue);params.push('emptyvalue='+emptyvalue);console.log(params);ajxpgn('contactformcontainer',url+'ajx_contactform.php?'+params.join('&')+'&formtype='+formtype,0,0,null,function(rq){if(rq.readyState==4){window.location.href='https://www.abacus.agency/thank-you/';}else{console.log('Failure to send form.');}});}
function contactformerror(msg){document.getElementById('errormsg').style='color:red';document.getElementById('errormsg').innerHTML=msg;}
function valstr(d){if(d.value==''){d.style.borderColor='red';return false;}
return true;}
function valemail(d){if(d.value=='x'||d.value.replace(/\S+@\S+\.\S+/g,'x')!='x'){d.style.borderColor='red';return false;}
return true;}
function scrolltosection(id,base,top){var bm=document.getElementById(id).offsetTop;var base=document.getElementById(base).offsetTop;var b=base+bm-top;var st=document.documentElement.scrollTop;if(st<document.body.scrollTop)st=document.body.scrollTop;var frames=1000;var step=(b-st)/frames;var settop=function(target,t){setTimeout(function(){document.documentElement.scrollTop=target;document.body.scrollTop=target;},Math.sqrt(t/100)*200);}
for(var i=1;i<=frames;i++){settop(st+step*i,i);}}
function listblogposts(el,url){var blogfilters=document.getElementById('blogfilters');var filters=blogfilters.querySelectorAll('.categoryitem');el.className+=' activetab';for(i=0;i<=filters.length-1;i++){filters[i].isActive=0;el.isActive=1;if(filters[i].className.includes('activetab')&&!filters[i].isActive){filters[i].className='categoryitem';}}
ajxpgn('blogindex_section',url+'ajx_listblogposts.inc.php?');}
function filterblogposts(el,postcategoryid,url){var blogfilters=document.getElementById('blogfilters');var filters=blogfilters.querySelectorAll('.categoryitem');el.className+=' activetab';for(i=0;i<=filters.length-1;i++){filters[i].isActive=0;el.isActive=1;if(filters[i].className.includes('activetab')&&!filters[i].isActive){filters[i].className='categoryitem';}}
ajxpgn('blogindex_section',url+'ajx_filterblogposts.inc.php?categoryid='+postcategoryid);}
function nextblogposts(offset,categoryid,url){ajxpgn('blogindex_section',url+'ajx_nextblogposts.inc.php?offset='+offset+'&catid='+categoryid);}
function expandcontainer(el,classname){var bannerbg=document.getElementById('bannerbg');var headergoldline=document.getElementById('headergoldline');if(!el.isopen){el.className+=' expanded';el.isopen=true;bannerbg.style.height='900px';headergoldline.style.top='43%'}else{el.className=classname;el.isopen=null;bannerbg.style.height='500px';headergoldline.style.top='50%'}}